# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6067b3119947011f2fbd84567cecc7596848ca3e42867609a49d95ba9d552dc06f16622738c5cfcca4e5fef1024d27c23809045b0f0f1db93bf522e9e6f8398e

test:
  secret_key_base: a040a6f04d51a5133ef8b55ad244af0bc640f70f3a2b6e9d79f55dde3d5647aff7c0e2c4293abca2b6fa6d9a51577fb826a5aed27c963c2c7a89654b85ddaf2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
